[package]
name = "sdl2_sys_simple"
version = "0.0.1"
authors = ["XorTroll"]

[dependencies.nx-rs]
git = "https://github.com/rusty-horizon/nx-rs"
features = []

[dependencies.sdl2-sys]
git = "https://github.com/rusty-horizon/switch-sdl2-sys"
branch = "master"
features = []
